require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*

Layout/AlignHash:
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - francis_cms.gemspec

Metrics/LineLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
