require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - francis_cms.gemspec

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
