AllCops:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - '**/francis_cms.gemspec'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
