AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - '**/francis_cms.gemspec'

Metrics/LineLength:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
